sudo: required
language: python

python:
  - "2.7"

env:
- TCL_VERSION=8.5.0

addons:
  apt:
    packages:
    - tcl8.5
    - tk8.5
    - tcl8.5-dev
    - tk8.5-dev

install:
        - pip install cython matplotlib pillow pytest-cov coverage coveralls

before_script:
    - sudo apt-get install swig
    - export OOMMF_PREFIX=${OOMMF_PREFIX:-$HOME}
    - bash -x .travis/install-oommf.sh
    - export OOMMF_PATH=/home/travis/oommf

# command to run tests
script:
- which tclsh
- which oommf
- $OOMMF_PATH/oommf.tcl +platform


script: 
- coverage run --source joommf -m py.test
after_success: coveralls


notifications:
  slack: finmag:7HxjIcZF9CPe0sIS5CQJGK08


