sudo: required
language: python

python:
  - "2.7"

env:
- TCL_VERSION=8.6.0

addons:
  apt:
    packages:
    - tcl8.6
    - tk8.6
    - tcl8.6-dev
    - tk8.6-dev

install:
        - pip install cython matplotlib pillow pytest-cov coverage

before_script:
    - sudo apt-get install swig
    - export OOMMF_PREFIX=${OOMMF_PREFIX:-$HOME}
    - bash -x .travis/install-oommf.sh
    - export OOMMF_PATH=/home/travis/oommf

# command to run tests
script:
- which tclsh
- which oommf
- $OOMMF_PATH/oommf.tcl +platform


script: make test



notifications:
  slack: finmag:7HxjIcZF9CPe0sIS5CQJGK08
