sudo: required
language: python

python:
  - "3.5"

env:
- TCL_VERSION=8.5.0

addons:
  apt:
    packages:
    - tcl8.5
    - tk8.5
    - tcl8.5-dev
    - tk8.5-dev

install:
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  - conda info -a
  - conda create -n test-environment python=$TRAVIS_PYTHON_VERSION cython matplotlib pillow pytest
  - source activate test-environment; pip install pytest-cov coverage coveralls pandas

before_script:
  - export OOMMF_PREFIX=${OOMMF_PREFIX:-$HOME}
  - bash -x .travis/install-oommf.sh
  - export OOMMF_PATH=/home/travis/oommf

# command to run tests
script:
  - which tclsh
  - which oommf
  - $OOMMF_PATH/oommf.tcl +platform


script:
  - coverage run --source joommf -m py.test

after_success: 
  - coveralls


notifications:
  slack: finmag:7HxjIcZF9CPe0sIS5CQJGK08


