language: python
python:
  - "2.7"
  # - "3.4"
  # - "3.5"

notifications:
  slack: finmag:7HxjIcZF9CPe0sIS5CQJGK08

install:
        - pip install cython matplotlib PIL --allow-external PIL --allow-unverified PIL

before_script:
  - sudo apt-get install swig 

# command to install dependencies
# install: "pip install -r requirements.txt"
# command to run tests

script: make test-other-wrapping-cpp
script: make test-vision-oommf
